INSERT INTO Classroom (id, trainer, trainerID) VALUES (1, 'John Doe', 25687)

INSERT INTO Trainee(id, traineeName) VALUES (1, 'John')
INSERT INTO Trainee(id, traineeName) VALUES (2, 'Manish') 
INSERT INTO Trainee(id, traineeName) VALUES (3, 'Seth')

INSERT INTO CLASSROOM_TRAINEE(CLASSROOM_ID, TRAINEELIST_ID) VALUES (1, 1)
INSERT INTO CLASSROOM_TRAINEE(CLASSROOM_ID, TRAINEELIST_ID) VALUES (1, 2)
INSERT INTO CLASSROOM_TRAINEE(CLASSROOM_ID, TRAINEELIST_ID) VALUES (1, 3)